# Stage 1: Build
FROM alpine:3.23 AS builder

RUN apk add --no-cache \
    build-base \
    cmake \
    git

WORKDIR /mpqcli

COPY . .

RUN cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DMPQCLI_BUILD_APP=ON \
    -DMPQCLI_BUILD_STATIC=ON

RUN cmake --build build

RUN strip build/bin/mpqcli

# Stage 2: Create a minimal runtime image
FROM scratch AS runtime

COPY --from=builder /mpqcli/build/bin/mpqcli /mpqcli

ENTRYPOINT ["/mpqcli"]
