name: Lint

on:
  workflow_call

jobs:
  lint_cpp:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install clang tools
        run: make install_clang_tools

      - run: make fmt_check

      - run: make lint_cpp
