name: Main

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - ".clang-format"
      - ".clang-tidy"
      - "src/**"
      - "extern/**"
      - "test/**"
      - "CMakeLists.txt"
      - "Dockerfile.glibc"
      - "Dockerfile.musl"

concurrency:
  group: prerelease
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    uses: ./.github/workflows/lint.yml
    needs: build
  test:
    uses: ./.github/workflows/test.yml
    needs: build
  prerelease:
    uses: ./.github/workflows/prerelease.yml
    needs: 
      - build
      - lint
      - test
    secrets: inherit
