name: Push

on:
  push

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    uses: ./.github/workflows/release.yml
    needs: build
    secrets: inherit
