name: Tag and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: build
  release:
    uses: ./.github/workflows/release.yml
    needs: 
      - build
      - test
    secrets: inherit 
